# Generated by Django 5.1.7 on 2025-03-30 05:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='specialite',
        ),
        migrations.AddField(
            model_name='customuser',
            name='date_naissance',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='specialitemedi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth_core.specialitemedicale'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='temporary_password',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='agents_sante',
            field=models.CharField(blank=True, choices=[('admin', 'Admin'), ('docteur', 'Docteur'), ('infirmier', 'Infirmier'), ('laborantin', 'Laborantin')], max_length=20),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='medical_license',
            field=models.FileField(blank=True, upload_to='medical_licenses/'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='specialitelabo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth_core.specialitelaboratoire'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(max_length=100),
        ),
    ]
