# Generated by Django 5.1.7 on 2025-03-30 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_core', '0002_remove_customuser_specialite_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='medical_license',
            field=models.FileField(blank=True, null=True, upload_to='medical_licenses/'),
        ),
    ]
