# Generated by Django 5.1.7 on 2025-03-30 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_core', '0003_alter_customuser_medical_license'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='numero_licence_medicale',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
