# Generated by Django 5.1.7 on 2025-04-08 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_core', '0005_alter_customuser_numero_licence_medicale'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_rejected',
            field=models.BooleanField(default=False),
        ),
    ]
