# Generated by Django 5.1.7 on 2025-04-08 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_core', '0006_customuser_is_rejected'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='rejection_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='rejection_reason',
            field=models.TextField(blank=True),
        ),
    ]
