# Generated by Django 5.1.7 on 2025-03-31 15:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomPatient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numerodossier', models.CharField(blank=True, max_length=8, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('civilite', models.CharField(blank=True, choices=[('M', 'Monsieur'), ('Mme', 'Madame')], max_length=20)),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('adresse', models.CharField(blank=True, max_length=200, null=True)),
                ('ville', models.CharField(blank=True, max_length=100, null=True)),
                ('contact', models.CharField(max_length=10)),
                ('contact_urgence', models.CharField(blank=True, max_length=10, null=True)),
                ('stade_mrc', models.CharField(blank=True, choices=[('state1', 'State1'), ('state2', 'State2'), ('state3', 'State3'), ('state4', 'State4'), ('state5', 'State5')], max_length=20)),
                ('docteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Patient',
            },
        ),
    ]
