# Generated by Django 5.1.7 on 2025-04-08 23:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='custompatient',
            options={'ordering': ['-date_creation'], 'verbose_name': 'Patient'},
        ),
        migrations.AddField(
            model_name='custompatient',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
