# Generated by Django 5.1.7 on 2025-04-09 11:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0004_rendezvous'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='rendez_vous',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultations', to='patient.rendezvous'),
        ),
        migrations.CreateModel(
            name='AnalyseAFaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_analyse', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('statut', models.CharField(choices=[('A_FAIRE', 'À faire'), ('EN_COURS', 'En cours'), ('TERMINE', 'Terminé')], default='A_FAIRE', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_prevue', models.DateField(blank=True, null=True)),
                ('consultation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='analyses_a_faire', to='patient.consultation')),
                ('dossier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses_a_faire', to='patient.dossiermedical')),
                ('laboratin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ResultatAnalyse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_saisie', models.DateTimeField(auto_now_add=True)),
                ('creatinine', models.FloatField(blank=True, null=True)),
                ('potassium', models.FloatField(blank=True, null=True)),
                ('dgf', models.FloatField(blank=True, null=True)),
                ('poids', models.FloatField(blank=True, null=True)),
                ('tension_systolique', models.IntegerField(blank=True, null=True)),
                ('tension_diastolique', models.IntegerField(blank=True, null=True)),
                ('analyse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultats', to='patient.analyseafaire')),
                ('laborantin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analyses_saisies', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultats', to='patient.custompatient')),
            ],
        ),
        migrations.CreateModel(
            name='Alerte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_alerte', models.CharField(choices=[('CRITIQUE', 'Critique'), ('MODEREE', 'Modérée')], max_length=20)),
                ('message', models.TextField()),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('envoyee', models.BooleanField(default=False)),
                ('resultat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertes', to='patient.resultatanalyse')),
            ],
        ),
    ]
