# Generated by Django 5.1.7 on 2025-04-10 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0006_remove_dossiermedical_resume_medical_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='custompatient',
            old_name='contact',
            new_name='phone_number',
        ),
    ]
