# Generated by Django 5.1.7 on 2025-04-10 05:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patient', '0007_rename_contact_custompatient_phone_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('stade_mrc', models.CharField(blank=True, choices=[('state1', 'State1'), ('state2', 'State2'), ('state3', 'State3'), ('state4', 'State4'), ('state5', 'State5')], max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('docteur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflows', to=settings.AUTH_USER_MODEL)),
                ('laborantin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflows_laborantin', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TacheWorkflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_tache', models.CharField(choices=[('ANALYSE', 'Saisie de résultats'), ('RAPPEL', 'Rappel patient'), ('ALERTE', 'Détection anomalie')], max_length=20)),
                ('description', models.CharField(max_length=200)),
                ('intervalle', models.CharField(blank=True, choices=[(None, 'Aucun'), ('hourly', 'Horaire'), ('daily', 'Quotidien'), ('weekly', 'Hebdomadaire'), ('monthly', 'Mensuel')], default=None, help_text='Intervalle de récurrence pour les tâches répétitives', max_length=20, null=True)),
                ('seuil_critique', models.JSONField(blank=True, null=True)),
                ('message_alerte', models.TextField(blank=True)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taches', to='workflows.workflow')),
            ],
        ),
        migrations.CreateModel(
            name='PatientWorkflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_assignation', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflows', to='patient.custompatient')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patients', to='workflows.workflow')),
            ],
            options={
                'unique_together': {('patient', 'workflow')},
            },
        ),
    ]
